### ISSUE TITLE
Avoid setting unnecessary data is avoiding setting required data

### ISSUE THREAD

**Issue by nedlukies** [trappar/AliceGenerator#7]
Inside \Trappar\AliceGenerator\ValueVisitor there is a test to see if the value from the entity is the same as the initial value. For null, bool and object types it does a strict comparison (===), for everything else it uses ==. I have schemas where the initial value is set to null, but the field value is often (int) 0. A non strict comparison will return true, hence these values will not be included in the generated fixture.

Adding integer into the list of types checked with a strict comparison solves the issue, but I am wondering if there is a better way to do this.

**Comment by trappar** [comment]
To be honest, I can't really remember why I have it doing the null/bool/object check, and not just using === in all cases. The tests pass just fine using === for everything, and in one large application I use this in the resulting changes to the fixtures are mostly due to situations where the schema isn't correctly setup - like where the doctrine type is `smallint` but the default value is `false`.

Can you think of any reason the strict comparison wouldn't be good in all cases?

I might sit on this for a day or two and see if I can come up with any reason not to make the change.

**Comment by trappar** [comment]
I've just tagged a new version which fixes this issue and provides a way to switch back to the old functionality.

https://github.com/trappar/AliceGenerator/releases/tag/v0.2.0

Thanks for reporting 😄
